---
title: "Untitled"
output: 
  github_document: 
   toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = '.', warning = FALSE, message = FALSE, 
                      fig.path = "img/rifampin_midazolam_ddi-")
```

```{r}
library(mrgsolve)
library(tidyverse)
library(PKPDmisc)
theme_set(theme_bw())
theme_update(legend.position = "top")
```

# Rifampin / Midazolam DDI Model

```{r}
mod <- mread_cache("rifampicin_midazolam", "models", delta = 0.1)
```


- Single dose
```{r}
rif <- ev(amt = 600)
rif
```


```{r}
mod %>%
  ev(rif) %>% 
  Req(Ccentral) %>%
  mrgsim(end = 48) %>% 
  plot()
```


- Multiple dose ... What's going on here?
```{r}
rif <- mutate(rif, ii = 24, addl = 9)

rif

out <- 
  mod %>%
  ev(rif) %>% 
  mrgsim(end = 240)

plot(out, Ccentral ~ time)

```


- Anything else?
 
```{r}
out %>% 
 mutate(DAY = 1+floor(time/24)) %>%
 group_by(DAY) %>% 
 summarise(AUC = auc_partial(time,Ccentral)) %>% 
 ungroup %>% 
 mutate(pAUC = 100*AUC/first(AUC))
```


```{r}
simsm <- 
  out %>%
  as_data_frame() %>%
  gather(variable, value, c(UGT_ratio_HC5, CYP3A4_ratio_HC5))

simsm %>%
  ggplot(., aes(time, value, col = variable)) + 
  geom_line(lwd =1 ) + scale_color_brewer(palette = "Set2") 
```







